# Generated by Django 5.1.3 on 2024-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('home_away', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=10)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
